version: '3.7'
services:
  flask:
    build: ./flask
    container_name: flask
    networks:
      - cicd-networks
    expose:
      - 5000
  nginx:
    build: ./nginx
    container_name: nginx
    networks:
      - cicd-networks
    ports:
      - "80:80"
networks:
  cicd-networks:
    driver: bridge
