version: '3.7'
services:
  flask_app:
    build: ./flask
    container_name: flask
    networks:
      - cicd-networks
    ports:
      - "8000:8000"
    expose:
      - "8000"
      
  nginx:
    build: ./nginx
    container_name: nginx
    networks:
    - cicd-networks
    ports:
      - "80:80"
    depends_on:
      - flask_app
networks:
  cicd-networks:
    driver: bridge
