name: CI/CD Pipeline

on:
  push:
    branches:
      - staging

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker HUB
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push flask image
        uses: docker/build-push-action@v3
        with:
          context: ./flask
          file: ./flask/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest

      - name: build and push nginx image
        uses: docker/build-push-action@v3
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest
